# coding: utf-8

"""
    Seller API Promotion

    Synchronization from the database runs every 3 minutes.  <br>The status is changed once per 1 minute. During this interval the last status change action will be saved. <br>The bid change takes place once in 30 seconds. Within this interval the last action to change the bid will be saved.   # noqa: E501

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from promotion.api_client import ApiClient


class ManagingTheParametersOfASearchCampaignApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def adv_v0_active_get(self, id, subject_id, status, **kwargs):  # noqa: E501
        """Changing the activity of the object group for a search campaign  # noqa: E501

        The method allows to change the activity of the object group for search campaign.<br> Changing the activity is only available for campaigns in status 9 or 11. <br>A maximum of 5 requests per second is allowed.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v0_active_get(id, subject_id, status, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: Campaing ID (required)
        :param int subject_id: The ID of the object group for which the activity changes (required)
        :param str status: New state (`true` - make the group active or `false` - make the group inactive) (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.adv_v0_active_get_with_http_info(id, subject_id, status, **kwargs)  # noqa: E501
        else:
            (data) = self.adv_v0_active_get_with_http_info(id, subject_id, status, **kwargs)  # noqa: E501
            return data

    def adv_v0_active_get_with_http_info(self, id, subject_id, status, **kwargs):  # noqa: E501
        """Changing the activity of the object group for a search campaign  # noqa: E501

        The method allows to change the activity of the object group for search campaign.<br> Changing the activity is only available for campaigns in status 9 or 11. <br>A maximum of 5 requests per second is allowed.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v0_active_get_with_http_info(id, subject_id, status, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: Campaing ID (required)
        :param int subject_id: The ID of the object group for which the activity changes (required)
        :param str status: New state (`true` - make the group active or `false` - make the group inactive) (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'subject_id', 'status']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method adv_v0_active_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `adv_v0_active_get`")  # noqa: E501
        # verify the required parameter 'subject_id' is set
        if ('subject_id' not in params or
                params['subject_id'] is None):
            raise ValueError("Missing the required parameter `subject_id` when calling `adv_v0_active_get`")  # noqa: E501
        # verify the required parameter 'status' is set
        if ('status' not in params or
                params['status'] is None):
            raise ValueError("Missing the required parameter `status` when calling `adv_v0_active_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501
        if 'subject_id' in params:
            query_params.append(('subjectId', params['subject_id']))  # noqa: E501
        if 'status' in params:
            query_params.append(('status', params['status']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['HeaderApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/adv/v0/active', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def adv_v1_search_set_excluded_post(self, body, id, **kwargs):  # noqa: E501
        """Setting/removing minus phrases from search for a search campaign  # noqa: E501

        The method allows to set/remove minus-phrases for search. <br> Sending an empty array removes all minus-phrases from the Search ad campaign. <br> 2 requests per second are allowed.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v1_search_set_excluded_post(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SearchSetexcludedBody body: (required)
        :param int id: Campaing ID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.adv_v1_search_set_excluded_post_with_http_info(body, id, **kwargs)  # noqa: E501
        else:
            (data) = self.adv_v1_search_set_excluded_post_with_http_info(body, id, **kwargs)  # noqa: E501
            return data

    def adv_v1_search_set_excluded_post_with_http_info(self, body, id, **kwargs):  # noqa: E501
        """Setting/removing minus phrases from search for a search campaign  # noqa: E501

        The method allows to set/remove minus-phrases for search. <br> Sending an empty array removes all minus-phrases from the Search ad campaign. <br> 2 requests per second are allowed.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v1_search_set_excluded_post_with_http_info(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SearchSetexcludedBody body: (required)
        :param int id: Campaing ID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method adv_v1_search_set_excluded_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `adv_v1_search_set_excluded_post`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `adv_v1_search_set_excluded_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['HeaderApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/adv/v1/search/set-excluded', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def adv_v1_search_set_phrase_post(self, body, id, **kwargs):  # noqa: E501
        """Setting/removing minus-phrase of phrase matching for search campaign  # noqa: E501

        The method allows to set/remove minus-phrase phrases of a phrase match. <br> Posting an empty array removes all minus-phrase of phrase matching from the campaign. <br> A maximum of 2 requests per second is allowed.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v1_search_set_phrase_post(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SearchSetphraseBody body: (required)
        :param int id: Campaing ID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.adv_v1_search_set_phrase_post_with_http_info(body, id, **kwargs)  # noqa: E501
        else:
            (data) = self.adv_v1_search_set_phrase_post_with_http_info(body, id, **kwargs)  # noqa: E501
            return data

    def adv_v1_search_set_phrase_post_with_http_info(self, body, id, **kwargs):  # noqa: E501
        """Setting/removing minus-phrase of phrase matching for search campaign  # noqa: E501

        The method allows to set/remove minus-phrase phrases of a phrase match. <br> Posting an empty array removes all minus-phrase of phrase matching from the campaign. <br> A maximum of 2 requests per second is allowed.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v1_search_set_phrase_post_with_http_info(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SearchSetphraseBody body: (required)
        :param int id: Campaing ID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method adv_v1_search_set_phrase_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `adv_v1_search_set_phrase_post`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `adv_v1_search_set_phrase_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['HeaderApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/adv/v1/search/set-phrase', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def adv_v1_search_set_plus_get(self, id, **kwargs):  # noqa: E501
        """Managing the activity of fixed phrases in search campaigns  # noqa: E501

        The method allows to change the activity of fixed phrases in search campaigns.  <br>  1 request per 500 milliseconds is allowed.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v1_search_set_plus_get(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: Campaing ID (required)
        :param bool fixed: New state (`false` - make inactive, `true` - make active)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.adv_v1_search_set_plus_get_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.adv_v1_search_set_plus_get_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def adv_v1_search_set_plus_get_with_http_info(self, id, **kwargs):  # noqa: E501
        """Managing the activity of fixed phrases in search campaigns  # noqa: E501

        The method allows to change the activity of fixed phrases in search campaigns.  <br>  1 request per 500 milliseconds is allowed.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v1_search_set_plus_get_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: Campaing ID (required)
        :param bool fixed: New state (`false` - make inactive, `true` - make active)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'fixed']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method adv_v1_search_set_plus_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `adv_v1_search_set_plus_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501
        if 'fixed' in params:
            query_params.append(('fixed', params['fixed']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['HeaderApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/adv/v1/search/set-plus', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def adv_v1_search_set_plus_post(self, body, id, **kwargs):  # noqa: E501
        """Setting/deleting fixed phrases in search campaigns  # noqa: E501

        The method allows to set and delete fixed phrases.  <br> Sending an empty array removes all fixed phrases and disables fixed phrase activity in the campaign.<br> 2 requests per second are allowed.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v1_search_set_plus_post(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SearchSetplusBody body: (required)
        :param int id: Campaing ID (required)
        :return: list[str]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.adv_v1_search_set_plus_post_with_http_info(body, id, **kwargs)  # noqa: E501
        else:
            (data) = self.adv_v1_search_set_plus_post_with_http_info(body, id, **kwargs)  # noqa: E501
            return data

    def adv_v1_search_set_plus_post_with_http_info(self, body, id, **kwargs):  # noqa: E501
        """Setting/deleting fixed phrases in search campaigns  # noqa: E501

        The method allows to set and delete fixed phrases.  <br> Sending an empty array removes all fixed phrases and disables fixed phrase activity in the campaign.<br> 2 requests per second are allowed.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v1_search_set_plus_post_with_http_info(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SearchSetplusBody body: (required)
        :param int id: Campaing ID (required)
        :return: list[str]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method adv_v1_search_set_plus_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `adv_v1_search_set_plus_post`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `adv_v1_search_set_plus_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['HeaderApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/adv/v1/search/set-plus', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[str]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def adv_v1_search_set_strong_post(self, body, id, **kwargs):  # noqa: E501
        """Setting/removing minus exact match phrases for a search campaign  # noqa: E501

        The method allows to set/remove minus-phrases of exact match. <br> Sending an empty array removes all minus-phrases of the exact match from the ad campaign.  <br> 2 requests per second are allowed.          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v1_search_set_strong_post(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SearchSetstrongBody body: (required)
        :param int id: Campaing ID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.adv_v1_search_set_strong_post_with_http_info(body, id, **kwargs)  # noqa: E501
        else:
            (data) = self.adv_v1_search_set_strong_post_with_http_info(body, id, **kwargs)  # noqa: E501
            return data

    def adv_v1_search_set_strong_post_with_http_info(self, body, id, **kwargs):  # noqa: E501
        """Setting/removing minus exact match phrases for a search campaign  # noqa: E501

        The method allows to set/remove minus-phrases of exact match. <br> Sending an empty array removes all minus-phrases of the exact match from the ad campaign.  <br> 2 requests per second are allowed.          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v1_search_set_strong_post_with_http_info(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SearchSetstrongBody body: (required)
        :param int id: Campaing ID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method adv_v1_search_set_strong_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `adv_v1_search_set_strong_post`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `adv_v1_search_set_strong_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['HeaderApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/adv/v1/search/set-strong', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def adv_v1_search_supplier_products_get(self, **kwargs):  # noqa: E501
        """List of items for a search campaign  # noqa: E501

        The method returns a list of products that are available. These items can be added to the campaign. <span class=\"newM\">new</span> <br> To get all products that are in stock, it is necessary to send a request without the parameter<code>subject</code>. <br> <br> 1 request per 12 seconds is allowed.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v1_search_supplier_products_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int subject: Subject ID
        :return: list[InlineResponse20026]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.adv_v1_search_supplier_products_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.adv_v1_search_supplier_products_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def adv_v1_search_supplier_products_get_with_http_info(self, **kwargs):  # noqa: E501
        """List of items for a search campaign  # noqa: E501

        The method returns a list of products that are available. These items can be added to the campaign. <span class=\"newM\">new</span> <br> To get all products that are in stock, it is necessary to send a request without the parameter<code>subject</code>. <br> <br> 1 request per 12 seconds is allowed.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v1_search_supplier_products_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int subject: Subject ID
        :return: list[InlineResponse20026]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['subject']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method adv_v1_search_supplier_products_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'subject' in params:
            query_params.append(('subject', params['subject']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['HeaderApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/adv/v1/search/supplier-products', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[InlineResponse20026]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def adv_v1_search_supplier_subjects_get(self, **kwargs):  # noqa: E501
        """A list of items for the search campaign  # noqa: E501

        The method allows to get the list of seller's items and the number of WB articles for each item. <span class=\"newM\">new</span> <br> 1 request per 12 seconds is allowed.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v1_search_supplier_subjects_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[InlineResponse20025]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.adv_v1_search_supplier_subjects_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.adv_v1_search_supplier_subjects_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def adv_v1_search_supplier_subjects_get_with_http_info(self, **kwargs):  # noqa: E501
        """A list of items for the search campaign  # noqa: E501

        The method allows to get the list of seller's items and the number of WB articles for each item. <span class=\"newM\">new</span> <br> 1 request per 12 seconds is allowed.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.adv_v1_search_supplier_subjects_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[InlineResponse20025]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method adv_v1_search_supplier_subjects_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['HeaderApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/adv/v1/search/supplier-subjects', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[InlineResponse20025]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
