from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from promotion.api.activity_api import ActivityApi
from promotion.api.bids_api import BidsApi
from promotion.api.dictionaries_api import DictionariesApi
from promotion.api.finances_api import FinancesApi
from promotion.api.managing_the_general_parameters_of_a_campaign_api import ManagingTheGeneralParametersOfACampaignApi
from promotion.api.managing_the_parameters_of_a_auto_campaign_api import ManagingTheParametersOfAAutoCampaignApi
from promotion.api.managing_the_parameters_of_a_search_campaign_api import ManagingTheParametersOfASearchCampaignApi
from promotion.api.media_api import MediaApi
from promotion.api.promotion_api import PromotionApi
from promotion.api.statistics_api import StatisticsApi
