# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.38
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.v0038_partitions_response import V0038PartitionsResponse

class TestV0038PartitionsResponse(unittest.TestCase):
    """V0038PartitionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0038PartitionsResponse:
        """Test V0038PartitionsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0038PartitionsResponse`
        """
        model = V0038PartitionsResponse()
        if include_optional:
            return V0038PartitionsResponse(
                meta = openapi_client.models.v0/0/38_meta.v0.0.38_meta(
                    plugin = openapi_client.models.v0_0_38_meta_plugin.v0_0_38_meta_plugin(
                        type = '', 
                        name = '', ), 
                    slurm = openapi_client.models.v0_0_38_meta_slurm.v0_0_38_meta_Slurm(
                        version = openapi_client.models.v0_0_38_meta_slurm_version.v0_0_38_meta_Slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', ), ),
                errors = [
                    openapi_client.models.v0/0/38_error.v0.0.38_error(
                        error = '', 
                        error_number = 56, )
                    ],
                partitions = [
                    openapi_client.models.v0/0/38_partition.v0.0.38_partition(
                        flags = [
                            ''
                            ], 
                        preemption_mode = [
                            ''
                            ], 
                        allowed_allocation_nodes = '', 
                        allowed_accounts = '', 
                        allowed_groups = '', 
                        allowed_qos = '', 
                        alternative = '', 
                        billing_weights = '', 
                        default_memory_per_cpu = 56, 
                        default_time_limit = 56, 
                        denied_accounts = '', 
                        denied_qos = '', 
                        preemption_grace_time = 56, 
                        maximum_cpus_per_node = 56, 
                        maximum_memory_per_node = 56, 
                        maximum_nodes_per_job = 56, 
                        max_time_limit = 56, 
                        min_nodes_per_job = 56, 
                        name = '', 
                        nodes = '', 
                        over_time_limit = 56, 
                        priority_job_factor = 56, 
                        priority_tier = 56, 
                        qos = '', 
                        state = '', 
                        total_cpus = 56, 
                        total_nodes = 56, 
                        tres = '', 
                        maximum_memory_per_cpu = 56, 
                        default_memory_per_node = 56, )
                    ]
            )
        else:
            return V0038PartitionsResponse(
        )
        """

    def testV0038PartitionsResponse(self):
        """Test V0038PartitionsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
