# generated by scripts/generate_messages.py

from twnet_parser.pretty_print import PrettyPrint
from typing import Literal

class MsgForwardResponse(PrettyPrint):
    def __init__(
            self
    ) -> None:
        self.message_type: Literal['connless'] = 'connless'
        self.message_name: str = 'connless.forward_response'
        self.message_id: list[int] = [255, 255, 255, 255, 102, 119, 33, 33]


    # first byte of data
    # has to be the first byte of the message payload
    # NOT the chunk header and NOT the message id
    def unpack(self, data: bytes) -> bool:
        return True

    def pack(self) -> bytes:
        return b''