
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-09T08:28:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b419d5fe6079975dbc6ccbca13b128c52709f3f",
 "version": "0.0.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
