# coding: utf-8

"""
    Seller API Feedbacks and Questions

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20013Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_name': 'str',
        'file': 'str',
        'content_type': 'str'
    }

    attribute_map = {
        'file_name': 'fileName',
        'file': 'file',
        'content_type': 'contentType'
    }

    def __init__(self, file_name=None, file=None, content_type=None):  # noqa: E501
        """InlineResponse20013Data - a model defined in Swagger"""  # noqa: E501
        self._file_name = None
        self._file = None
        self._content_type = None
        self.discriminator = None
        if file_name is not None:
            self.file_name = file_name
        if file is not None:
            self.file = file
        if content_type is not None:
            self.content_type = content_type

    @property
    def file_name(self):
        """Gets the file_name of this InlineResponse20013Data.  # noqa: E501

        File name  # noqa: E501

        :return: The file_name of this InlineResponse20013Data.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this InlineResponse20013Data.

        File name  # noqa: E501

        :param file_name: The file_name of this InlineResponse20013Data.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    @property
    def file(self):
        """Gets the file of this InlineResponse20013Data.  # noqa: E501

        File  # noqa: E501

        :return: The file of this InlineResponse20013Data.  # noqa: E501
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this InlineResponse20013Data.

        File  # noqa: E501

        :param file: The file of this InlineResponse20013Data.  # noqa: E501
        :type: str
        """

        self._file = file

    @property
    def content_type(self):
        """Gets the content_type of this InlineResponse20013Data.  # noqa: E501

        Content type  # noqa: E501

        :return: The content_type of this InlineResponse20013Data.  # noqa: E501
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this InlineResponse20013Data.

        Content type  # noqa: E501

        :param content_type: The content_type of this InlineResponse20013Data.  # noqa: E501
        :type: str
        """

        self._content_type = content_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20013Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20013Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
