# coding: utf-8

"""
    Seller API Feedbacks and Questions

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20014Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'feedbacks': 'ResponseFeadback'
    }

    attribute_map = {
        'feedbacks': 'feedbacks'
    }

    def __init__(self, feedbacks=None):  # noqa: E501
        """InlineResponse20014Data - a model defined in Swagger"""  # noqa: E501
        self._feedbacks = None
        self.discriminator = None
        if feedbacks is not None:
            self.feedbacks = feedbacks

    @property
    def feedbacks(self):
        """Gets the feedbacks of this InlineResponse20014Data.  # noqa: E501


        :return: The feedbacks of this InlineResponse20014Data.  # noqa: E501
        :rtype: ResponseFeadback
        """
        return self._feedbacks

    @feedbacks.setter
    def feedbacks(self, feedbacks):
        """Sets the feedbacks of this InlineResponse20014Data.


        :param feedbacks: The feedbacks of this InlineResponse20014Data.  # noqa: E501
        :type: ResponseFeadback
        """

        self._feedbacks = feedbacks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20014Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20014Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
