# coding: utf-8

# flake8: noqa
"""
    Statistics

    Methods to get different reports. For Paid storage report, send a request to generate it, and then a request to get it. other report are available immediately, without pre-generation.   # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from wildberries_api_client.statistics.models.detail_report_item import DetailReportItem
from wildberries_api_client.statistics.models.download_request import DownloadRequest
from wildberries_api_client.statistics.models.error_response import ErrorResponse
from wildberries_api_client.statistics.models.incomes_item import IncomesItem
from wildberries_api_client.statistics.models.inline_response429 import InlineResponse429
from wildberries_api_client.statistics.models.one_ofinline_response429 import OneOfinlineResponse429
from wildberries_api_client.statistics.models.orders_item import OrdersItem
from wildberries_api_client.statistics.models.response429 import Response429
from wildberries_api_client.statistics.models.response_error_statistics import ResponseErrorStatistics
from wildberries_api_client.statistics.models.sales_item import SalesItem
from wildberries_api_client.statistics.models.stocks_item import StocksItem
