word_replacements = {
    "mt": "metric tonns",
    "mts": "metric tonns",
    "dwt": "deadweight",
    "vsl": "vessel",
    "mv": "merchant vessel",
    "m/v" : "merchant vessel",
    "pct": "percent",
    "cons": "consumption",
    "blt" : "built",
    "vlsfo" : "very low sulfur fuel oil",
    "ulsfo":"ultra low sulfur fuel oil",
    "ifo": "intermediate fuel oil",
    "mgo": "marine gas oil",
    "lsmgo" : "light sulfur marine gas oil",
    "dwat":"deadweight",
    "s.dwat" : "summer deadweight",
    "cr" : "cranes",
    "ho" : "holds",
    "ha" : "hatches",
    "ho/ha" : "holds and hatches",
    "loa":"length overall",
    "bod":"bunker on delivery",
    "del" : "delivery",
    "dely" : "delivery",
    "delvy" : "delivery",
    "redel":"re delivery",
    "rdl" : "re delivery",
    "add" : "address",
    "ad" : "address",
    "comm":"commission",
    "com" : "commission",
    "tct" : "time charter",
    "lbp" : "length between perpendiculars",
    "blt":"built",
    "l/c" : "lycan",
    "acct" : "account",
    "pmax" : "panamax",
    "kmax":"kamsarmax",
    "kamax":"kamsarmax",
    "abt" : "about",
    "gt" : "gross tonnage",
    "grt":"gross tonnage",
    "nrt" : "net tonnage",
    "nt" : "net tonnage",
    "kt" : "knots",
    "kts" : "knots",
    "no":"number",
    "no.":"number",
    "crgo":"cargo",
    "tt" : "total",
    "hk" : "hong kong",
    "tpc" : "tonnes per centimeter",
    "ttl" : "total",
    "fwd" : "forward",
    "blst" : "ballast",
    "bl" : "ballast",
    "flg" : "flag",
    "wrkg":"working",
    "wkng" : 'working',
    "wrkng" : 'working',
    "cbm" : "cubic meter",
    "smx" : "supramax",
    "umx":"ultramax",
    'kmx':'kamsarmax',
    "blk" :"bulk",
    "jpn" : "japan",
    "adc":"address commission",
    "adcc":"address commission",
    "addcom" : "address commission",
    "dlosp" : "dropping last outward sea pilot",
    "lay" : "laycan",
    "addcomm" : "address commission",
    'addcom':"address commission",
    "bm" : "beam",
    "ordrs":"orders",
    "ordr":"order",
    "sp" : "singapore",
    'rm': 'residual marine',
    'ecsa' : 'east coast of south america',
    "spore": 'singapore',
    "alt"  : "alternative",
    "voy" : "voyage",
    's.china' : "south china",
    'schina' : "south china",
    'n.china' : "north china",
    'nchina' : "north china",
    "plsd" : "pleased",
    "rgds" : "regards",
    "brgds":"best regards",
    "shinc":"sundays and holidays included",
    "sshinc" : "saturdays sundays and holidays included",
    "sshex": "saturdays sundays and holidays excluded",
    "eta" : "expected to arrive",
    "hh":"holds and hatches",
    "dft":"draft",
    "wog" : "without guarantee",
    'bss' : 'beaufort sea state',
    "o/a" : "on or about",
    "wcca":"west coast of centeral america",
    "pls" : "please",
    "pus" : "possible uplift surcharge",
    "wci" : "west coast of india",
    "pps" : "please provide suggestions",
    "cst" : "cost",
    "eca" : "emission control area",
    "opn" : "open",
    "a/e" : "auxiliary engine",
    "qtty" : "quantity",
    "qty" : "quantity",
    "mos" : "month",
    "owrs" : "owners",
    "yrs" : 'years',
    "est":"east",
    "｜｜天好海运有限责任公司" : "",
    "adcomm" : "address commission",
    "hrs" : "hours",
    "gd" : "good",
    "gdday" : "good day",
    "pwwd" : "per weather working day",
    "tn" : "tonns",
    "blw" : "below",
    "req" : "required",
    "fhinc" : "fridays and holdiays included",
    "mtons" : "metric tonns",
    "acc" : "account",
    "goodday" : "good day",
    "sld" : "sailed",
    "onw" : "onwards",
    "dur" : "duration",
    "ppose":"please provide suggestions",
    "kns":"knots"
    }
