from nltk.corpus import wordnet as wn

mapper = {'CC': None,
           'CD': wn.NOUN,
           'DT': None,
           'EX': wn.ADV,
           'FW': None,
           'IN': wn.ADV,
           'JJ': [wn.ADJ, wn.ADJ_SAT],
           'JJR': [wn.ADJ, wn.ADJ_SAT],
           'JJS': [wn.ADJ, wn.ADJ_SAT],
           'LS': None,
           'MD': None,
           'NN': wn.NOUN,
           'NNS': wn.NOUN,
           'NNP': wn.NOUN,
           'NNPS': wn.NOUN,
           'PDT': [wn.ADJ, wn.ADJ_SAT],
           'POS': None,
           'PRP': None,
           'PRP$': None,
           'RB': wn.ADV,
           'RBR': wn.ADV,
           'RBS': wn.ADV,
           'RP': [wn.ADJ, wn.ADJ_SAT],
           'SYM': None,
           'TO': None,
           'UH': None,
           'VB': wn.VERB,
           'VBD': wn.VERB,
           'VBG': wn.VERB,
           'VBN': wn.VERB,
           'VBP': wn.VERB,
           'VBZ': wn.VERB
           }