# Generated by Django 4.1.2 on 2023-04-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_keyword_delete_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='negation',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='description',
            field=models.CharField(blank=True, help_text='just a description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(help_text='keyword name', max_length=200),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='options',
            field=models.CharField(blank=True, help_text='what type of field is it, does it has sub fields', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='stage',
            field=models.CharField(blank=True, help_text='where will the keyword element will appeare in snort builder', max_length=100, null=True),
        ),
    ]
