# DO NOT MODIFY -- This file is generated by type_spec
# flake8: noqa: F821
# ruff: noqa: E402
# fmt: off
# isort: skip_file
from __future__ import annotations
import typing  # noqa: F401
import datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from dataclasses import dataclass

__all__: list[str] = [
    "Arguments",
    "Data",
    "ENDPOINT_METHOD",
    "ENDPOINT_PATH",
    "InputWithName",
]

ENDPOINT_METHOD = "GET"
ENDPOINT_PATH = "api/external/inputs/external_get_input_names"


# DO NOT MODIFY -- This file is generated by type_spec
@dataclass(kw_only=True)
class Arguments:
    material_family_id: int
    offset: typing.Optional[int]
    is_parameter: typing.Optional[bool]
    limit: typing.Optional[int]


# DO NOT MODIFY -- This file is generated by type_spec
@dataclass(kw_only=True)
class InputWithName:
    input_id: int
    name: str


# DO NOT MODIFY -- This file is generated by type_spec
@dataclass(kw_only=True)
class Data:
    inputs: list[InputWithName]
# DO NOT MODIFY -- This file is generated by type_spec
