# coding: utf-8

"""
    Cashfree Payout APIs

    Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2024-01-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import cashfree_payout
from cashfree_payout.models.create_beneficiary_request_beneficiary_instrument_details import CreateBeneficiaryRequestBeneficiaryInstrumentDetails  # noqa: E501
from cashfree_payout.rest import ApiException

class TestCreateBeneficiaryRequestBeneficiaryInstrumentDetails(unittest.TestCase):
    """CreateBeneficiaryRequestBeneficiaryInstrumentDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateBeneficiaryRequestBeneficiaryInstrumentDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBeneficiaryRequestBeneficiaryInstrumentDetails`
        """
        model = cashfree_payout.models.create_beneficiary_request_beneficiary_instrument_details.CreateBeneficiaryRequestBeneficiaryInstrumentDetails()  # noqa: E501
        if include_optional :
            return CreateBeneficiaryRequestBeneficiaryInstrumentDetails(
                bank_account_number = '00111122233', 
                bank_ifsc = 'HDFC0000001', 
                vpa = 'test@upi'
            )
        else :
            return CreateBeneficiaryRequestBeneficiaryInstrumentDetails(
        )
        """

    def testCreateBeneficiaryRequestBeneficiaryInstrumentDetails(self):
        """Test CreateBeneficiaryRequestBeneficiaryInstrumentDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
