# coding: utf-8

"""
    Nomad Envoy

    This is the API descriptor for the Nomad Envoy API, responsible for order operation and product lists. Developed by [Samarkand Global](https://samarkand.global) in partnership with [Youzan](https://www.youzan.com/), [LittleRED](https://www.xiaohongshu.com/), [PDD](http://www.pinduoduo.com/), etc. Read the documentation online at [Nomad API Suite](https://api.samarkand.io/). - Install for node with `npm install nomad_envoy_cli` - Install for python with `pip install nomad-envoy-cli`  # noqa: E501

    The version of the OpenAPI document: 1.58.0
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import nomad_envoy_cli
from nomad_envoy_cli.models.order_api_response import OrderApiResponse  # noqa: E501
from nomad_envoy_cli.rest import ApiException

class TestOrderApiResponse(unittest.TestCase):
    """OrderApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OrderApiResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = nomad_envoy_cli.models.order_api_response.OrderApiResponse()  # noqa: E501
        if include_optional :
            return OrderApiResponse(
                code = 56, 
                message = '0', 
                connector_responses = [
                    nomad_envoy_cli.models.api_response_connector_response.ApiResponseConnectorResponse(
                        input = '0', 
                        mapping_name = 'GetProductMapping', 
                        api = [
                            '0'
                            ], 
                        api_doc_link = 'https://open.pinduoduo.com/#/apidocument/port?portId=pdd.goods.commit.detail.get', 
                        http_request_raw_data = '-', 
                        code = 56, 
                        response = '0', 
                        response_en = '0', 
                        platform = 'youzan', 
                        request_count = 1, 
                        response_time = 1000, )
                    ], 
                response_time = 1000, 
                data = null
            )
        else :
            return OrderApiResponse(
        )

    def testOrderApiResponse(self):
        """Test OrderApiResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
