from _typeshed import Incomplete
from amsdal.migration.utils import object_schema_to_table_schema as object_schema_to_table_schema
from amsdal.schemas.manager import SchemaManager as SchemaManager
from amsdal_data.table_schemas.manager import TableSchemasManager
from amsdal_models.classes.manager import ClassManager
from amsdal_models.classes.model import Model
from amsdal_models.schemas.data_models.schema import ObjectSchema
from amsdal_utils.models.enums import SchemaTypes

class MigrationManager:
    _schema_manager: Incomplete
    _table_schemas_manager: Incomplete
    _class_manager: Incomplete
    def __init__(self, schema_manager: SchemaManager, table_schema_manager: TableSchemasManager, class_manager: ClassManager) -> None: ...
    def run_migrations(self) -> None: ...
    def refresh_state_db(self) -> None: ...
    def _refresh_state_db(self, base_model: type[Model]) -> None: ...
    def migrate_class(self, object_schema: ObjectSchema, base_class: type[Model], schema_type: SchemaTypes, *, skip_data_migrations: bool = False) -> tuple[Model, bool]: ...
    def _register_class_version(self, object_schema: ObjectSchema, class_version: str = '', *, create_table: bool = False) -> None: ...
    def _migrate_class_objects(self, class_name: str, prior_version: str, new_version: str, schema_type: SchemaTypes) -> None: ...
