from setuptools import setup, find_packages
# todo: sort out the code for training
setup(
    name = 'lmsleepdata',
    version = '0.2.2.3',
    keywords='eeg sleep staging analysis',
    description = 'a python analyse tool for LM Data Recorder data',
    license = 'MIT License',
    url = 'https://github.com/eegion/lmsleepdata',
    author = 'quanlan',
    author_email = 'dev@eegion.com',
    packages = find_packages(),
    include_package_data = True,
    platforms = 'any',
    install_requires = ['scipy>=1.10.1',
                        'matplotlib>=3.3.4',
                        'seaborn>=0.12.2',
                        'numpy>=1.23.5',
                        'numba==0.56.4',
                        'pandas>=2.0.2',
                        'mne==1.4.0',
                        'scikit-learn>=1.2.2',
                        'lightgbm==3.3.5',
                        'antropy==0.1.4',
                        'lspopt>=1.3.0',
                        'openpyxl>=3.1.2',
                        'reportlab>=4.0.4',
                        'pillow>=10.0.0',
                        'redis>=3.5.3'],
)