
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-11T21:57:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "63c158fdb580891b285914e3f9ffa586dcc86e40",
 "version": "1.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
