
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-11T22:06:58+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "11e13944be794fa2a66f39775bc619425669de6d",
 "version": "8.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
