# coding: utf-8

"""
    Seller API Promotion

    Synchronization from the database runs every 3 minutes.  <br>The status is changed once per 1 minute. During this interval the last status change action will be saved. <br>The bid change takes place once in 30 seconds. Within this interval the last action to change the bid will be saved.   # noqa: E501

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V0IntervalsBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'advert_id': 'int',
        'intervals': 'list[Advv0intervalsIntervals]',
        'param': 'int'
    }

    attribute_map = {
        'advert_id': 'advertId',
        'intervals': 'intervals',
        'param': 'param'
    }

    def __init__(self, advert_id=None, intervals=None, param=None):  # noqa: E501
        """V0IntervalsBody - a model defined in Swagger"""  # noqa: E501
        self._advert_id = None
        self._intervals = None
        self._param = None
        self.discriminator = None
        self.advert_id = advert_id
        self.intervals = intervals
        self.param = param

    @property
    def advert_id(self):
        """Gets the advert_id of this V0IntervalsBody.  # noqa: E501

        Campaing ID  # noqa: E501

        :return: The advert_id of this V0IntervalsBody.  # noqa: E501
        :rtype: int
        """
        return self._advert_id

    @advert_id.setter
    def advert_id(self, advert_id):
        """Sets the advert_id of this V0IntervalsBody.

        Campaing ID  # noqa: E501

        :param advert_id: The advert_id of this V0IntervalsBody.  # noqa: E501
        :type: int
        """
        if advert_id is None:
            raise ValueError("Invalid value for `advert_id`, must not be `None`")  # noqa: E501

        self._advert_id = advert_id

    @property
    def intervals(self):
        """Gets the intervals of this V0IntervalsBody.  # noqa: E501

        An array of new values for intervals. <br> The maximum number of intervals is `24`.   # noqa: E501

        :return: The intervals of this V0IntervalsBody.  # noqa: E501
        :rtype: list[Advv0intervalsIntervals]
        """
        return self._intervals

    @intervals.setter
    def intervals(self, intervals):
        """Sets the intervals of this V0IntervalsBody.

        An array of new values for intervals. <br> The maximum number of intervals is `24`.   # noqa: E501

        :param intervals: The intervals of this V0IntervalsBody.  # noqa: E501
        :type: list[Advv0intervalsIntervals]
        """
        if intervals is None:
            raise ValueError("Invalid value for `intervals`, must not be `None`")  # noqa: E501

        self._intervals = intervals

    @property
    def param(self):
        """Gets the param of this V0IntervalsBody.  # noqa: E501

        The parameter for which the change will be made must be the value of `subjectId` (for campaigns in search and recommendations) or `setId` (for campaigns in the product card)   # noqa: E501

        :return: The param of this V0IntervalsBody.  # noqa: E501
        :rtype: int
        """
        return self._param

    @param.setter
    def param(self, param):
        """Sets the param of this V0IntervalsBody.

        The parameter for which the change will be made must be the value of `subjectId` (for campaigns in search and recommendations) or `setId` (for campaigns in the product card)   # noqa: E501

        :param param: The param of this V0IntervalsBody.  # noqa: E501
        :type: int
        """
        if param is None:
            raise ValueError("Invalid value for `param`, must not be `None`")  # noqa: E501

        self._param = param

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V0IntervalsBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0IntervalsBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
