# coding: utf-8

# flake8: noqa

"""
    Seller API Recommendations

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from recommendations.api.recommendations_api import RecommendationsApi
# import ApiClient
from recommendations.api_client import ApiClient
from recommendations.configuration import Configuration
# import models into sdk package
from recommendations.models.inline_response200 import InlineResponse200
from recommendations.models.inline_response200_data import InlineResponse200Data
from recommendations.models.v1_del_body import V1DelBody
from recommendations.models.v1_ins_body import V1InsBody
from recommendations.models.v1_set_body import V1SetBody
