# Autogenerated by devscripts/update-version.py

__version__ = '2024.03.08.232718'

RELEASE_GIT_HEAD = 'f4f9f6d00edcac6d4eb2b3fb78bf81326235d492'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.03.08.232718dev'
