# Generated by Django 4.1.2 on 2023-04-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snort', '0006_rename_main_ref_snortrule_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snortrule',
            name='tag',
            field=models.BooleanField(default=True, help_text="add 'tag:session,10,packets' to rule"),
        ),
    ]
