# Generated by Django 5.0.2 on 2024-02-23 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_source'),
        ('snort', '0008_snortrule_exported_snortrule_sensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='snortrule',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.source'),
        ),
    ]
