
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-12T16:24:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c109b657f3b1fdb6bece3b89c9717dacefd25a03",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
