
from typing import Optional
from .. import AffTree

def ReLU(dim: int) -> 'AffTree': ...

def partial_ReLU(dim: int, row: int) -> 'AffTree': ...

def argmax(dim: int) -> 'AffTree': ...

def class_characterization(dim: int, clazz: int) -> 'AffTree': ...

def inf_norm(dim: int, minimum: Optional[float], maximum: Optional[float]) -> 'AffTree': ...
