# DO NOT MODIFY -- This file is generated by type_spec
# flake8: noqa: F821
# ruff: noqa: E402
# fmt: off
# isort: skip_file
from __future__ import annotations
import typing  # noqa: F401
import datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from dataclasses import dataclass

__all__: list[str] = [
    "Arguments",
    "Data",
    "ENDPOINT_METHOD",
    "ENDPOINT_PATH",
    "FullRecipeMetadataField",
]

ENDPOINT_METHOD = "GET"
ENDPOINT_PATH = "api/external/recipe_metadata/external_get_recipe_metadata_data"


# DO NOT MODIFY -- This file is generated by type_spec
@dataclass(kw_only=True)
class Arguments:
    material_family_id: int
    recipe_metadata_ids: typing.Optional[list[int]]
    offset: typing.Optional[int]
    limit: typing.Optional[int]


# DO NOT MODIFY -- This file is generated by type_spec
@dataclass(kw_only=True)
class FullRecipeMetadataField:
    recipe_metadata_id: int
    name: str
    quantity_type: str


# DO NOT MODIFY -- This file is generated by type_spec
@dataclass(kw_only=True)
class Data:
    recipe_metadata: list[FullRecipeMetadataField]
# DO NOT MODIFY -- This file is generated by type_spec
