
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-08T13:47:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6fb25db36ce4732478855520d75b4224a0cb067",
 "version": "1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
