
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-11T13:00:20+0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0043562b77acd79f254cbd3496ecbbf9fc8cd519",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
