# Generated by Django 3.2.22 on 2023-10-30 03:22

import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.statuses
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0098_rename_data_jobresult_result'),
        ('nautobot_plugin_w_rrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitattributes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='circuitattributes',
            name='tags',
            field=nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='locationattributes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationattributes',
            name='tags',
            field=nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='radioattributes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='radioattributes',
            name='status',
            field=nautobot.extras.models.statuses.StatusField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radio_attributes', to='extras.status'),
        ),
        migrations.AlterField(
            model_name='radioattributes',
            name='tags',
            field=nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
