# Generated by Django 3.2.24 on 2024-02-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_plugin_w_rrm', '0002_auto_20231030_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitattributes',
            name='human_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='locationattributes',
            name='human_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='radioattributes',
            name='human_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
