
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-08T01:43:38+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "35c2c63c7da9f17f8d44d3a4a9cced2519bc02d5",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
