
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-07T14:21:47-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ebd0d61dd95f204423141724ee18cdd92faebbc9",
 "version": "3.0.2.post0.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
