# coding: utf-8

"""
    Seller API Content

    Queries limits: <dd>Maximum of 100 requests per minute to all Content methods are allowed.</dd> <br> Public API for Content is designed for server-to-server data synchronization between Wildberries and Suppliers. <br> You download data from Wildberries to your computing resources for further operating it. <br> <code>It is not allowed to use the Content API as an external database. If you exceed the requests limits, access to the API will be restricted.</code> <br> <br> <br>   # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20017Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cards': 'list[InlineResponse20017DataCards]',
        'cursor': 'InlineResponse20017DataCursor'
    }

    attribute_map = {
        'cards': 'cards',
        'cursor': 'cursor'
    }

    def __init__(self, cards=None, cursor=None):  # noqa: E501
        """InlineResponse20017Data - a model defined in Swagger"""  # noqa: E501
        self._cards = None
        self._cursor = None
        self.discriminator = None
        if cards is not None:
            self.cards = cards
        if cursor is not None:
            self.cursor = cursor

    @property
    def cards(self):
        """Gets the cards of this InlineResponse20017Data.  # noqa: E501

        The list of requested product cards  # noqa: E501

        :return: The cards of this InlineResponse20017Data.  # noqa: E501
        :rtype: list[InlineResponse20017DataCards]
        """
        return self._cards

    @cards.setter
    def cards(self, cards):
        """Sets the cards of this InlineResponse20017Data.

        The list of requested product cards  # noqa: E501

        :param cards: The cards of this InlineResponse20017Data.  # noqa: E501
        :type: list[InlineResponse20017DataCards]
        """

        self._cards = cards

    @property
    def cursor(self):
        """Gets the cursor of this InlineResponse20017Data.  # noqa: E501


        :return: The cursor of this InlineResponse20017Data.  # noqa: E501
        :rtype: InlineResponse20017DataCursor
        """
        return self._cursor

    @cursor.setter
    def cursor(self, cursor):
        """Sets the cursor of this InlineResponse20017Data.


        :param cursor: The cursor of this InlineResponse20017Data.  # noqa: E501
        :type: InlineResponse20017DataCursor
        """

        self._cursor = cursor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20017Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20017Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
