# Autogenerated by nbdev

d = { 'settings': { 'branch': 'machn',
                'doc_baseurl': '/achn',
                'doc_host': 'https://dsm-72.github.io',
                'git_url': 'https://github.com/dsm-72/achn',
                'lib_path': 'achn'},
  'syms': { 'achn.core': { 'achn.core.achn': ('core.html#achn', 'achn/core.py'),
                           'achn.core.achn.__call__': ('core.html#achn.__call__', 'achn/core.py'),
                           'achn.core.achn.__getattr__': ('core.html#achn.__getattr__', 'achn/core.py'),
                           'achn.core.achn.__init__': ('core.html#achn.__init__', 'achn/core.py'),
                           'achn.core.achn.able': ('core.html#achn.able', 'achn/core.py'),
                           'achn.core.achn.call': ('core.html#achn.call', 'achn/core.py'),
                           'achn.core.achn.chain': ('core.html#achn.chain', 'achn/core.py'),
                           'achn.core.identity': ('core.html#identity', 'achn/core.py')}}}
