class CppBridge:
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def delete_byte_array(cls, buffer: int) -> None: ...
    @classmethod
    def init_logging(cls, usage: str) -> None: ...
    @classmethod
    def load_gurobi_shared_library(cls, full_library_path: str) -> bool: ...
    @classmethod
    def set_flags(cls, flags: CppFlags) -> None: ...
    @classmethod
    def shutdown_logging(cls) -> None: ...

class CppFlags:
    cp_model_dump_lns: bool
    cp_model_dump_models: bool
    cp_model_dump_prefix: str
    cp_model_dump_response: bool
    log_prefix: bool
    stderrthreshold: int
    def __init__(self) -> None: ...

class OrToolsVersion:
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def major_number(cls) -> int: ...
    @classmethod
    def minor_number(cls) -> int: ...
    @classmethod
    def patch_number(cls) -> int: ...
    @classmethod
    def version_string(cls) -> str: ...
