# -*- coding: utf-8 -*-

VALUES_MAPS = {

    'repere_map': {
        '0': 'Liège (avant fusion)',
        '1': 'Angleur (avant fusion)',
        '2': 'Bressoux (avant fusion)',
        '3': 'Chênée (avant fusion)',
        '4': 'Glain (avant fusion)',
        '5': 'Grivegnée (avant fusion)',
        '6': 'Jupille (avant fusion)',
        '7': 'Rocourt (avant fusion)',
        '8': 'Sclessin (avant fusion)',
        '9': 'Wandre (avant fusion)',
        '11': 'St-Nicolas (avant fusion)',
        '12': 'Vottem (avant fusion)',
        '13': 'Ans (avant fusion)',
        '14': 'Divers (avant fusion)',
        '0/0': 'Liège (après fusion)',
        '0/1': 'Angleur (après fusion)',
        '0/2': 'Bressoux (apès fusion)',
        '0/3': 'Chênée (après fusion)',
        '0/4': 'Glain (après fusion)',
        '0/5': 'Grivegnée (après fusion)',
        '0/6': 'Jupille (après fusion)',
        '0/7': 'Rocourt (après fusion)',
        '0/8': 'Sclessin (après fusion)',
        '0/9': 'Wandre (après fusion)',
        '11/0': 'St-Nicolas (après fusion)',
        '12/0': 'Vottem (après fusion)',
        '13/0': 'Ans (après fusion)',
        '14/0': 'Divers (après fusion)',
        'avt1910': 'Liège (avant 1910)',
        '0/1 0/3': 'Angleur/Chénée',
        '0/0  0/2': 'Liège/Bressoux',
        '0/0 0/4': 'Liège/Glain',
        '0/0  0/4 11/0': 'Liège/Glain/StNicolas',
        '0/0 0/7 13/0': 'Liège/Rocourt/Ans',
        '0/0 13/0': 'Liège/Ans',
        '0/1 0/3 0/0': 'Liège/Angleur/Chénée',
        '0/2 0/5': 'Bresooux/Grivegnée',
        '0/5 0/6': 'Grivegnée/Jupille',
        '0/6 0/9': 'Jupille/Wandre',
        '0/7 13/0': 'Rocourt/Ans',
        '0/8 11/0': 'Sclessin/StNicolas',
        '0/0 12/0': 'Liège/Vottem',
        '0/3 0/5': 'Chénée/Grivegnée',
    }
}
