
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-08T09:50:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ca6148d79de64c90bda6b5af8a4b9be535a095d",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
