from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from wildberries_api_client.feedbacks_questions.api.feedbacks_api import FeedbacksApi
from wildberries_api_client.feedbacks_questions.api.questions_api import QuestionsApi
from wildberries_api_client.feedbacks_questions.api.templates_for_questions_and_reviews_api import TemplatesForQuestionsAndReviewsApi
